name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check if only README was modified
        id: check_readme
        run: |
          FILES_CHANGED=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})

          if [[ ! "$FILES_CHANGED" =~ ^README.md$ ]]; then
            echo "Not only README.md was changed. Proceeding with build."
            echo "should_proceed=true" >> $GITHUB_ENV
          else
            echo "Only README.md was changed. Skipping build."
            echo "should_proceed=false" >> $GITHUB_ENV
          fi

      - name: Checkout
        uses: actions/checkout@v4
      - name: Extract Docker image metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ vars.DOCKER_USERNAME }}/hiddenservice:latest
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        if: env.should_proceed == 'true'
        uses: docker/build-push-action@v6
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          annotations: ${{ steps.meta.outputs.annotations }}
          provenance: true
          sbom: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7 
